<?php

// autoload_static.php @generated by Composer
namespace Composer\Autoload;

class ComposerStaticInit0ac28a70b5320a14aed12375806e84af
{

    public static $prefixLengthsPsr4 = array(
        'Z' => array(
            'Zend\\Escaper\\' => 13
        ),
        'P' => array(
            'Library\\PHPWord\\' => 18,
            'Library\\Common\\' => 17
        )
    );

    public static $prefixDirsPsr4 = array(
        'Zend\\Escaper\\' => array(
            0 => __DIR__ . '/..' . '/Library/Framework'
        ),
        'PhpOffice\\PhpWord\\' => array(
            0 => __DIR__ . '/..' . '/Library/PHPWord/'
        ),
        'PhpOffice\\Common\\' => array(
            0 => __DIR__ . '/..' . '/Library/Common/'
        )
    );

    public static $classMap = array(
        'PclZip' => __DIR__ . '/..' . '/pclzip/pclzip/pclzip.lib.php'
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0ac28a70b5320a14aed12375806e84af::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0ac28a70b5320a14aed12375806e84af::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0ac28a70b5320a14aed12375806e84af::$classMap;
        }, null, ClassLoader::class);
    }
}
